title: "Brandon's Blog"
description: "Life Experience"
theme: minima

# 你的 GitHub Pages Project Pages 路徑
url: "https://brandon-git-hub.github.io"
baseurl: "/Blog"

# 讓 header 短小精幹
header_pages:
  - index.md
  - categories.md
